name: "Deploy Backend"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1 Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Setup Node.js (only for packaging if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3 Copy only important files to server
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: |
            package.json
            package-lock.json
            tsconfig.json
            nest-cli.json
            src/
            .env
          target: "/var/www/backend"
          strip_components: 0

      # 4 Install, build, and restart app directly on server
      - name: Install, Build, and Restart on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /var/www/backend
            npm ci
            npm run build
            pm2 delete backend || true
            pm2 start dist/main.js --name backend --env PORT=5000 --node-args="--experimental-global-webcrypto"
